"""Enrich descriptions for ideas 140-163 (labour, crime, justice)."""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data" / "new_ideas_batch.json"

ENRICHMENTS = {
    140: "The National Minimum Wage, set at R27.58 per hour in 2024, is reviewed annually by the National Minimum Wage Commission. Parliamentary hearings have examined whether the NMW has reduced in-work poverty or depressed employment in vulnerable sectors \u2014 agriculture and domestic work have lower sectoral rates. With strict unemployment at 31.9% (Q4 2024), the tension between adequate wages and employment absorption remains central. The committee has questioned the adequacy of the annual CPI-plus adjustment formula and whether it accounts for productivity differentials across sectors.",

    141: "The CCMA handles over 200,000 dispute cases annually but faces chronic under-resourcing, with commissioner vacancy rates above 20% in some regions. The committee has tracked rising caseloads, noting that conciliation settlement rates have declined from historic highs. Digitisation of case management and virtual hearings \u2014 accelerated during COVID \u2014 offer efficiency gains but require sustained investment. The 2025/26 BRRR recommended increased CCMA funding and faster commissioner appointments to reduce average case resolution times from the current 30+ days.",

    142: "The Employment Tax Incentive (ETI), introduced in 2014, provides wage subsidies to employers hiring workers aged 18-29 earning below R6,500/month. Treasury estimates the ETI supports approximately 700,000 jobs annually at a fiscal cost of ~R6bn. Parliamentary review has examined deadweight losses and proposals to expand eligibility beyond the current age and wage thresholds. With youth unemployment above 60%, the committee has debated whether a more generous or broader ETI could meaningfully shift the employment curve.",

    143: "The Unemployment Insurance Fund holds assets exceeding R200bn but has faced governance failures, investment losses, and processing delays. The committee has scrutinised quarterly performance, including the gap between contribution income and benefit payouts during mass retrenchment events. COVID-era TERS payments exposed systemic weaknesses in claims processing and fraud prevention. The fund is structurally sound financially but operationally dysfunctional \u2014 reforms focus on IT modernisation, claims automation, and investment governance aligned with the PIC Act.",

    144: "The Compensation Fund, which covers occupational injuries and diseases, has a claims backlog exceeding 100,000 cases and IT systems dating from the 1990s. The Auditor-General has issued consecutive adverse audit opinions. Employer non-compliance with registration and contributions compounds the backlog. Parliamentary oversight has documented systemic processing failures and the impact on injured workers who wait years for compensation. The committee has called for a comprehensive turnaround strategy including migration to modern digital claims management.",

    145: "South Africa has 8 million unemployed and an additional 4 million discouraged work-seekers \u2014 the highest unemployment rate among major economies. Active labour market programmes combining skills training, work experience, and placement services have been debated as an alternative to passive social transfers. The committee held dedicated workshops in 2025 on activation strategies, examining models from Brazil and India. The Presidential Youth Employment Intervention and Social Employment Fund represent existing activation efforts, but scale remains inadequate.",

    146: "Sections 189 and 189A of the Labour Relations Act govern large-scale retrenchments, requiring 60-day consultation periods and social plans for employers with 50+ employees. The committee held workshops in November 2025 examining whether current protections are adequate following major job losses in manufacturing and mining. Organised labour argues consultation periods are performative; business argues the process is too rigid for firms in genuine financial distress. Proposed amendments would strengthen mandatory social plan requirements while streamlining timelines for companies in business rescue.",

    147: "Productivity SA provides turnaround assistance to distressed companies, offering an alternative to retrenchment through workplace restructuring and competitiveness improvement. The entity operates on a modest budget (~R200m) relative to its potential impact. The committee has reviewed Productivity SA quarterly performance alongside CCMA and NEDLAC, noting that early intervention in struggling firms prevents the need for section 189 retrenchment processes. The 2025 BRRR recommended increased allocation to scale turnaround support, particularly for labour-intensive sectors facing structural transition.",

    148: "South Africa has approximately 3 million informal economy workers \u2014 street traders, waste pickers, domestic workers, and platform gig workers \u2014 most of whom lack basic labour protections, UIF coverage, or occupational health insurance. The committee has examined the gap between formal labour law and the reality of informally employed South Africans, including hearings on elder care, farm worker conditions, and CEDAW compliance. Platform work (e-hailing, delivery) has grown rapidly without clear regulatory coverage. Extending basic social security and dispute resolution to these workers is a recognised gap.",

    149: "NEDLAC, the tripartite social dialogue institution, brings government, business, labour, and community constituencies together to negotiate structural reform. The committee has monitored NEDLAC performance quarterly, noting both successes (minimum wage negotiations) and failures (stalled labour law amendments). A binding social compact on growth \u2014 modelled on the Irish social partnership model \u2014 would require wage moderation commitments from labour, investment commitments from business, and reform delivery from government.",

    150: "South Africa recorded over 27,000 murders in 2023/24, a rate of approximately 45 per 100,000 \u2014 among the highest globally. SAPS detective-to-case ratios in some provinces exceed 1:100, far above the recommended 1:25. The committee has documented critical shortages in forensic capacity, with DNA backlogs and ballistic analysis delays undermining prosecution success rates. The 2025/26 BRRR recommended ring-fenced funding for detective recruitment and forensic services modernisation as a prerequisite for improving the 20% serious crime conviction rate.",

    151: "Construction site extortion and business protection rackets have become a major barrier to infrastructure delivery, with the construction mafia disrupting projects worth billions of rands. The committee heard that over 80% of major construction sites in KwaZulu-Natal and Gauteng face extortion demands. Dedicated anti-extortion units, established in some provinces, have had mixed results due to the intersection of organised crime with local political structures. The committee has called for inter-departmental coordination between SAPS, NPA, and DTIC to protect infrastructure investment.",

    152: "South Africa has one of the highest rates of gender-based violence globally, with femicide rates five times the global average. The National Strategic Plan on GBVF (2020-2030) established targets including expanded Thuthuzela Care Centres, dedicated FCS units, and the National Register for Sex Offenders. The committee has examined implementation progress, noting police station-level compliance gaps with the Domestic Violence Act. The June 2025 hearings focused on systemic failures in victim support and the low conviction rates for sexual offences.",

    153: "IPID, the police oversight body, has faced institutional instability including leadership disputes documented in the February 2025 committee session. The directorate investigates deaths in custody, discharge of firearms, and corruption but has fewer than 500 investigators for 180,000+ SAPS members. Strengthening IPID operational independence is essential for police accountability, particularly given ongoing concerns about police brutality and extra-judicial killings. The committee has examined IPID caseloads relative to resources in quarterly performance reviews.",

    154: "South Africa has over 2.7 million registered private security officers \u2014 significantly more than the 180,000 SAPS members. PSIRA, the regulatory authority, oversees an industry worth ~R70bn annually. The committee has examined PSIRA regulatory effectiveness, including foreign ownership rules, training standards, and incidents involving security companies in community conflicts. Reform proposals include better coordination between private security and public policing, minimum qualification standards, and addressing the growing use of private security for essential public safety functions.",

    155: "Illegal mining (zama-zama operations) in abandoned mines poses severe safety, environmental, and security risks. The Stilfontein tragedy in late 2024, where hundreds of illegal miners were trapped underground, brought national attention to the issue. The committee received an illegal mining petition in September 2025 and has examined inter-departmental coordination failures between SAPS, DMRE, and the Department of Home Affairs. Combatting illegal mining requires addressing both the criminal syndicates that control operations and the desperate economic conditions that drive participation.",

    156: "Community Policing Forums (CPFs), mandated by the South African Police Service Act, are intended to enable civilian oversight and community safety partnerships at station level. In practice, most CPFs are underfunded and dysfunctional. The committee workshop in September 2025 examined revitalisation strategies, including sustainable funding models, integration with municipal Integrated Development Plans, and formal accountability mechanisms. The Civilian Secretariat for Police Service (CSPS) oversees CPF coordination but lacks enforcement capacity.",

    157: "The SANDF has been deployed in support of SAPS for internal security operations and border protection under successive Presidential authorisations. The March 2026 committee session examined the deployment alongside the Mkhwanazi Committee report on police-military coordination. Cost-effectiveness concerns persist \u2014 military deployments are expensive relative to equivalent police capacity. The committee has questioned whether permanent SANDF border deployment should be replaced with a dedicated border policing unit within SAPS.",

    158: "The NPA, under NDPP Shamila Batohi (appointed 2019), has made progress rebuilding prosecution capacity following the state capture era. The Investigating Directorate Against Corruption (IDAC), established as a permanent unit, has secured several high-profile convictions. However, the committee has tracked persistent vacancy rates in complex commercial crime units and the slow pace of Zondo Commission referral prosecutions. The June 2025 Annual Performance Plan review noted that NPA conviction rates have improved but remain below the 92% target in priority crime categories.",

    159: "Court case backlogs exceed 200,000 matters in the lower courts, with some criminal cases taking 3-5 years to reach trial. The committee has examined the causes: insufficient judicial officers, courtroom infrastructure in disrepair, and the impact of the COVID backlog that was never fully cleared. The Chief Justice has proposed case flow management reforms and expanded small claims jurisdiction. The November 2025 annual report review documented the gap between the Office of the Chief Justice modernisation plans and the Department of Justice budget allocation.",

    160: "The SIU Special Tribunal, established in 2019, enables civil recovery of state losses from corruption without criminal prosecution requirements. The committee has monitored recovery outcomes \u2014 the SIU has referred matters worth over R50bn but actual recoveries remain a fraction of this. The June 2025 session reviewed the SIU Annual Performance Plan alongside Legal Aid SA. Strengthening the Tribunal pipeline from investigation to recovery order to execution is the critical bottleneck, particularly for Digital Vibes and PPE-era corruption matters.",

    161: "Legal Aid South Africa provides legal representation to approximately 400,000 indigent clients annually but faces persistent funding constraints that limit coverage, particularly in rural areas and civil matters. The committee has examined the tension between Legal Aid mandate expansion and budget adequacy. Access to justice in family law, eviction, and administrative matters remains severely limited for poor South Africans, with implications for property rights, social grant access, and protection order enforcement.",

    162: "Implementation of outstanding TRC recommendations \u2014 including individual reparations, community rehabilitation, and prosecution of apartheid-era crimes \u2014 remains incomplete nearly three decades after the Commission reported. The committee held dedicated stakeholder engagements in May 2025, including with Deputy Ministers. Individual reparations of R30,000 per victim were paid in 2003 but have not been adjusted for inflation. Community reparations and symbolic measures have been sporadically implemented. The political economy of transitional justice has shifted as the original victim cohort ages.",

    163: "The Cybercrimes Act (2020) established a framework for criminalising cyber offences, preserving electronic evidence, and enabling international cooperation. Implementation has been slow \u2014 designated cybercrime courts are not yet operational, and SAPS digital forensic capacity remains limited. South Africa loses an estimated R2.2bn annually to cybercrime. The committee has examined readiness for Act enforcement, including capacity within the SAPS Hawks and coordination with the Information Regulator under POPIA.",
}

ideas = json.loads(DATA.read_text(encoding="utf-8"))

for idea in ideas:
    if idea["id"] in ENRICHMENTS:
        idea["description"] = ENRICHMENTS[idea["id"]]

DATA.write_text(json.dumps(ideas, indent=2, ensure_ascii=False), encoding="utf-8")

enriched = sum(1 for i in ideas if len(i["description"]) > 400)
print(f"Enriched: {enriched}/{len(ideas)} ideas have >400 char descriptions")
avg = sum(len(i["description"]) for i in ideas) // len(ideas)
print(f"Average description length: {avg} chars")
