"""
Seed new policy ideas from JSON into the local SQLite database.

Reads data/new_ideas_batch.json and inserts:
  - New policy_ideas rows
  - idea_meetings links (from matching_meetings in the JSON)

Also generates a Supabase-compatible SQL migration file.

Usage:
    python scripts/seed_new_ideas.py
"""

import json
import os
import sqlite3
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DB_PATH = os.environ.get(
    "SQLITE_DB_PATH",
    str(PROJECT_ROOT / "data" / "dev.sqlite3"),
)
IDEAS_JSON = PROJECT_ROOT / "data" / "new_ideas_batch.json"
MIGRATION_OUT = PROJECT_ROOT / "data" / "migrations" / "018_new_committees_data.sql"


def escape_sql(val: str) -> str:
    """Escape single quotes for SQL strings."""
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def main():
    if not IDEAS_JSON.exists():
        print(f"ERROR: {IDEAS_JSON} not found. Run extract_new_ideas.py first.")
        return

    ideas = json.loads(IDEAS_JSON.read_text(encoding="utf-8"))
    print(f"Loading {len(ideas)} ideas from {IDEAS_JSON}")

    db = sqlite3.connect(DB_PATH)

    # Ensure idea_meetings table exists
    db.execute("""
        CREATE TABLE IF NOT EXISTS idea_meetings (
            idea_id INTEGER NOT NULL,
            meeting_id INTEGER NOT NULL,
            PRIMARY KEY (idea_id, meeting_id)
        )
    """)

    inserted = 0
    linked = 0
    sql_lines = [
        "-- Migration 018: New committee ideas (Employment & Labour, Police, Justice, Water, Environment)",
        "-- Generated by scripts/seed_new_ideas.py",
        "",
    ]

    for idea in ideas:
        # Check if already exists
        existing = db.execute(
            "SELECT id FROM policy_ideas WHERE id = ?", (idea["id"],)
        ).fetchone()
        if existing:
            print(f"  Skip {idea['id']}: already exists")
            continue

        # Insert into SQLite
        db.execute(
            """
            INSERT INTO policy_ideas (
                id, title, description, binding_constraint, current_status,
                feasibility_rating, growth_impact_rating, time_horizon,
                reform_package, source_committee, responsible_department,
                slug, times_raised
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                idea["id"],
                idea["title"],
                idea["description"],
                idea["binding_constraint"],
                idea["current_status"],
                idea["feasibility_rating"],
                idea["growth_impact_rating"],
                idea["time_horizon"],
                idea["reform_package"],
                idea["source_committee"],
                idea["responsible_department"],
                idea["slug"],
                idea.get("times_raised", 0),
            ),
        )
        inserted += 1

        # Generate Supabase SQL
        sql_lines.append(
            f"INSERT INTO policy_ideas (id, title, description, binding_constraint, "
            f"current_status, feasibility_rating, growth_impact_rating, time_horizon, "
            f"reform_package, source_committee, responsible_department, slug, times_raised) VALUES ("
            f"{idea['id']}, {escape_sql(idea['title'])}, {escape_sql(idea['description'])}, "
            f"{escape_sql(idea['binding_constraint'])}, {escape_sql(idea['current_status'])}, "
            f"{idea['feasibility_rating']}, {idea['growth_impact_rating']}, "
            f"{escape_sql(idea['time_horizon'])}, {idea['reform_package']}, "
            f"{escape_sql(idea['source_committee'])}, {escape_sql(idea['responsible_department'])}, "
            f"{escape_sql(idea['slug'])}, {idea.get('times_raised', 0)});"
        )

        # Link to matching meetings
        for meeting in idea.get("matching_meetings", []):
            mid = meeting["meeting_id"]
            try:
                db.execute(
                    "INSERT OR IGNORE INTO idea_meetings (idea_id, meeting_id) VALUES (?, ?)",
                    (idea["id"], mid),
                )
                linked += 1
            except sqlite3.Error:
                pass  # meeting might not exist in DB

    db.commit()
    db.close()

    # Write migration file
    sql_lines.append("")
    MIGRATION_OUT.write_text("\n".join(sql_lines), encoding="utf-8")

    print(f"\nInserted {inserted} ideas, {linked} meeting links")
    print(f"Migration written to {MIGRATION_OUT}")

    # Summary
    print(f"\nTotal ideas in database:")
    db2 = sqlite3.connect(DB_PATH)
    total = db2.execute("SELECT COUNT(*) FROM policy_ideas").fetchone()[0]
    print(f"  {total} policy ideas")
    rows = db2.execute(
        "SELECT binding_constraint, COUNT(*) FROM policy_ideas GROUP BY binding_constraint ORDER BY COUNT(*) DESC"
    ).fetchall()
    for r in rows:
        print(f"  {r[1]:3d}  {r[0]}")
    db2.close()


if __name__ == "__main__":
    main()
